### ISSUE TITLE
軽くまとめた問題点

### ISSUE THREAD

**Issue by otofune** [MissKernel/Misskey#4]
# Misskey's Problems

※[こちら](https://gist.github.com/otofune/bb6b69cd8ece3a1783d4)が基となって作成されたIssueです。
### 未実装
- [x] About Misskeyページ - MissKernel/Misskey-Web#62
- [ ] Developers Centerページ - MissKernel/Misskey-Web#63
- [ ] Donateページ - MissKernel/Misskey-Web#64
- [ ] Likesページ - MissKernel/Misskey-Web#65
- [ ] E-Mail設定 - MissKernel/Misskey-Web#66
- [ ] Helpページ - MissKernel/Misskey-Web#67
- [ ] 掲示板機能 - #9
- [x] プロフィールページでの「すべて」「写真付き」「人気」ページ - MissKernel/Misskey-Web#72
- [ ] アルバムの容量表示機能 - MissKernel/Misskey-Web#68
- [ ] パスワード変更機能 - #10
- [ ] プロフィールのdescription - #12
- [ ] 部屋機能 - MissKernel/Misskey-Web#74
- [x] PCでのナビゲーションバーからの通知表示
- [ ] Unlike機能 - #8
### 表示がされない
- [x] プロフィール表示にて設定済みのURL/場所 - MissKernel/Misskey-Web#73
- [x] 日本語の含まれるURLがリンクにならない - MissKernel/Misskey-Web#69
### レイアウト崩れ
- [ ] 狭いウィンドウでのRepost - MissKernel/Misskey-Web#60
- [x] 自分のプロフィールページにてYouと★が中央からズレている - MissKernel/Misskey-Web#70
- [x] 長い長いURLによってページが崩れる - MissKernel/Misskey-Web#71

### 要望
- モバイルでの軽い投稿が改行できない - MissKernel/Misskey-Web#61
- 分かりやすい解説書 - #13
- データ書き出し機能 - #14

**Comment by otofune** [comment]
Gistのアップデートに伴い内容改変
- 未実装:description
- 要望から二つ要素をコメントアウト

**Comment by rinsuki** [comment]
リストをチェックボックスの方式にしたほうが進捗状況が表しやすいのではないでしょうか.
e.g.

``` md
* [ ] aaa
* [ ] bbb
```

**Comment by otofune** [comment]
ありがとうございます.確かにチェックボックスのほうがわかりやすいですね、次回更新からチェックボックス使ってみます.

**Comment by otofune** [comment]
これは要望で、データが消える恐れがあるのであればデータの書き出し機能なんかもあると良いかもしれないのと、Unlikeがどうにもできなさそうだったので追加

**Comment by syuilo** [comment]
Thnak you @AyaMorisawa
